version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true
  - cmd: git config --global core.symlinks true

clone_folder: c:\sireum

cache:
  - bin\scala
  - bin\win\graal
  - bin\win\java
  - bin\win\z3
  - cache\coursier

install:
  - git submodule update --init --recursive

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set COURSIER_CACHE=%APPVEYOR_BUILD_FOLDER%\cache\coursier
  - bin\build.cmd jitpack native
  - bin\win\upx.exe -9 bin\win\sireum.exe
  - bin\win\sireum.exe
