version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true
  - cmd: git config --global core.symlinks true

clone_folder: c:\sireum

cache:
  - bin\win\java
  - bin\scala
  - bin\win\z3

install:
  - git submodule update --init --recursive

build_script:
  - bin\build.cmd jitpack test
