jdk:
  - oraclejdk8
install:
  - cd $HOME
  - rm -fR .m2
  - echo $GIT_COMMIT
  - curl -JLo org.sireum.m2.zip https://github.com/sireum/rolling/releases/download/m2/org.sireum.m2-$GIT_COMMIT.zip
  - unzip org.sireum.m2.zip
  - rm org.sireum.m2.zip
