name: Distro

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  ci-distro-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
      - name: Update dev tag
        if: github.ref_type != 'tag'
        run: |
          cd "$GITHUB_WORKSPACE/kekinian"
          git push --force origin HEAD:refs/tags/dev
          git fetch --tags
      - name: Build Jar
        run: |
          cd "$GITHUB_WORKSPACE/kekinian"
          git submodule update --init --recursive
          cd "$GITHUB_WORKSPACE"
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/build.cmd"
          cp "$SIREUM_HOME/bin/sireum.jar" sireum.jar
      - name: Upload Jar dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum.jar
          asset_name: sireum.jar
          tag: dev
          overwrite: true
      - name: Upload Jar Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum.jar
          asset_name: sireum.jar
          tag: ${{ github.ref }}
          overwrite: true
      - name: Build
        run: |
          cd "$GITHUB_WORKSPACE"
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/install/vscodium.cmd" --extensions "ms-python.python,rust-lang.rust-analyzer"
          "$SIREUM_HOME/bin/build.cmd" native distro --linux --sfx
          mv "$SIREUM_HOME/bin/linux/sireum" sireum-cli-linux-amd64
          mv "$SIREUM_HOME/distro/linux.sfx" sireum-ive-linux-amd64.7z.sfx
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-linux-amd64
          asset_name: sireum-cli-linux-amd64
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-linux-amd64.7z.sfx
          asset_name: sireum-ive-linux-amd64.7z.sfx
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-linux-amd64
          asset_name: sireum-cli-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-linux-amd64.7z.sfx
          asset_name: sireum-ive-linux-amd64.7z.sfx
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-macos-arm64:
    runs-on: mac-mini-m1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/init.sh"
          "$SIREUM_HOME/bin/install/vscodium.cmd" --extensions "ms-python.python,rust-lang.rust-analyzer"
          "$SIREUM_HOME/bin/build.cmd" native distro --mac --sfx
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-cli-mac-arm64
          mv "$SIREUM_HOME/distro/mac.sfx" sireum-ive-mac-arm64.7z.sfx
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-arm64
          asset_name: sireum-cli-mac-arm64
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-arm64.7z.sfx
          asset_name: sireum-ive-mac-arm64.7z.sfx
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-arm64
          asset_name: sireum-cli-mac-arm64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-arm64.7z.sfx
          asset_name: sireum-ive-mac-arm64.7z.sfx
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-macos-amd64:
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/init.sh"
          "$SIREUM_HOME/bin/install/vscodium.cmd" --extensions "ms-python.python,rust-lang.rust-analyzer"
          "$SIREUM_HOME/bin/build.cmd" native distro --mac --sfx
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-cli-mac-amd64
          mv "$SIREUM_HOME/distro/mac.sfx" sireum-ive-mac-amd64.7z.sfx
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-amd64
          asset_name: sireum-cli-mac-amd64
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-amd64.7z.sfx
          asset_name: sireum-ive-mac-amd64.7z.sfx
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-amd64
          asset_name: sireum-cli-mac-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-amd64.7z.sfx
          asset_name: sireum-ive-mac-amd64.7z.sfx
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Enable git config core.longpaths
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"
      - name: Build
        shell: cmd
        run: |
          set SIREUM_HOME=%GITHUB_WORKSPACE%\kekinian
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call "%SIREUM_HOME%\bin\init.bat"
          call "%SIREUM_HOME%\bin\install\vscodium.cmd" --extensions "ms-python.python,rust-lang.rust-analyzer"
          call "%SIREUM_HOME%\bin\build.cmd" native distro --win --sfx
          move "%SIREUM_HOME%\bin\win\sireum.exe" "%GITHUB_WORKSPACE%\sireum-cli-win-amd64.exe"
          move "%SIREUM_HOME%\distro\win.exe" "%GITHUB_WORKSPACE%\sireum-ive-win-amd64.7z.exe"
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-win-amd64.exe
          asset_name: sireum-cli-win-amd64.exe
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-win-amd64.7z.exe
          asset_name: sireum-ive-win-amd64.7z.exe
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-win-amd64.exe
          asset_name: sireum-cli-win-amd64.exe
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-win-amd64.7z.exe
          asset_name: sireum-ive-win-amd64.7z.exe
          tag: ${{ github.ref }}
          overwrite: true
