name: Distro

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  ci-distro-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Native
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/build.cmd" native distro --linux --sfx
          mv "$SIREUM_HOME/bin/linux/sireum" sireum-cli-linux-amd64
          mv "$SIREUM_HOME/distro/linux.sfx" sireum-ive-linux-amd64.7z.sfx
      - name: Upload CLI Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-cli-linux-amd64
          path: sireum-cli-linux-amd64
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload IVE Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-ive-linux-amd64.7z.sfx
          path: sireum-ive-linux-amd64.7z.sfx
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
          include-hidden-files: false
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-linux-amd64
          asset_name: sireum-cli-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-linux-amd64.7z.sfx
          asset_name: sireum-ive-linux-amd64.7z.sfx
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-macos-arm64:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Native
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/build.cmd" native distro --mac --sfx
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-cli-mac-arm64
          mv "$SIREUM_HOME/distro/mac.sfx" sireum-ive-mac-arm64.7z.sfx
      - name: Upload CLI Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-cli-mac-arm64
          path: sireum-cli-mac-arm64
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload IVE Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-ive-mac-arm64.7z.sfx
          path: sireum-ive-mac-arm64.7z.sfx
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
          include-hidden-files: false
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-arm64
          asset_name: sireum-cli-mac-arm64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-arm64.7z.sfx
          asset_name: sireum-ive-mac-arm64.7z.sfx
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-macos-amd64:
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Native
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/kekinian"
          "$SIREUM_HOME/bin/build.cmd" native distro --mac --sfx
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-cli-mac-amd64
          mv "$SIREUM_HOME/distro/mac.sfx" sireum-ive-mac-amd64.7z.sfx
      - name: Upload CLI Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-cli-mac-amd64
          path: sireum-cli-mac-amd64
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload IVE Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-ive-mac-amd64.7z.sfx
          path: sireum-ive-mac-amd64.7z.sfx
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
          include-hidden-files: false
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-amd64
          asset_name: sireum-cli-mac-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-amd64.7z.sfx
          asset_name: sireum-ive-mac-amd64.7z.sfx
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: kekinian
          submodules: recursive
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"
      - name: Native
        shell: cmd
        run: |
          set SIREUM_HOME=%GITHUB_WORKSPACE%\kekinian
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call "%SIREUM_HOME%\bin\build.cmd" native distro --win --sfx
          move "%SIREUM_HOME%\bin\win\sireum.exe" "%GITHUB_WORKSPACE%\sireum-cli-win-amd64.exe"
          move "%SIREUM_HOME%\distro\win.exe" "%GITHUB_WORKSPACE%\sireum-ive-win-amd64.7z.exe"
      - name: Upload CLI Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-cli-win-amd64.exe
          path: sireum-cli-win-amd64.exe
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload IVE Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-ive-win-amd64.7z.exe
          path: sireum-ive-win-amd64.7z.exe
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
          include-hidden-files: false
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-win-amd64.exe
          asset_name: sireum-cli-win-amd64.exe
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-win-amd64.7z.exe
          asset_name: sireum-ive-win-amd64.7z.exe
          tag: ${{ github.ref }}
          overwrite: true
