name: Distro

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  ci-distro-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
      - name: Update dev tag
        if: github.ref_type != 'tag'
        run: |
          cd "$GITHUB_WORKSPACE/Sireum"
          git push --force origin HEAD:refs/tags/dev
          git fetch --tags
      - name: Build Jar
        run: |
          cd "$GITHUB_WORKSPACE/Sireum"
          git submodule update --init --recursive
          cd "$GITHUB_WORKSPACE"
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          "$SIREUM_HOME/bin/build.cmd"
          cp "$SIREUM_HOME/bin/sireum.jar" sireum.jar
      - name: Upload Jar dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum.jar
          asset_name: sireum.jar
          tag: dev
          overwrite: true
      - name: Upload Jar Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum.jar
          asset_name: sireum.jar
          tag: ${{ github.ref }}
          overwrite: true
      - name: Build
        run: |
          cd "$GITHUB_WORKSPACE"
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          "$SIREUM_HOME/bin/sireum" setup vscode --extensions "mhutchie.git-graph,ms-python.python,scalameta.metals,rust-lang.rust-analyzer"
          "$SIREUM_HOME/bin/build.cmd" native distro --linux --pack --vscodium
          mv "$SIREUM_HOME/bin/linux/sireum" sireum-cli-linux-amd64
          mv "$SIREUM_HOME/distro/linux.tar.xz" sireum-ive-linux-amd64.tar.xz
          mv "$SIREUM_HOME/distro/sireum-ive-vscodium-linux-amd64.tar.xz" .
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-linux-amd64
          asset_name: sireum-cli-linux-amd64
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-linux-amd64.tar.xz
          asset_name: sireum-ive-linux-amd64.tar.xz
          tag: dev
          overwrite: true
      - name: Upload HAMR dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-linux-amd64.tar.xz
          asset_name: sireum-ive-vscodium-linux-amd64.tar.xz
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-linux-amd64
          asset_name: sireum-cli-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-linux-amd64.tar.xz
          asset_name: sireum-ive-linux-amd64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload HAMR Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-linux-amd64.tar.xz
          asset_name: sireum-ive-vscodium-linux-amd64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-macos-arm64:
    runs-on: mac-mini-m1
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          submodules: recursive
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          "$SIREUM_HOME/bin/init.sh"
          "$SIREUM_HOME/bin/sireum" setup vscode --extensions "mhutchie.git-graph,ms-python.python,scalameta.metals,rust-lang.rust-analyzer"
          "$SIREUM_HOME/bin/build.cmd" native distro --mac --pack --vscodium
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-cli-mac-arm64
          mv "$SIREUM_HOME/distro/mac.tar.xz" sireum-ive-mac-arm64.tar.xz
          mv "$SIREUM_HOME/distro/sireum-ive-vscodium-mac-arm64.tar.xz" .
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-arm64
          asset_name: sireum-cli-mac-arm64
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-arm64.tar.xz
          asset_name: sireum-ive-mac-arm64.tar.xz
          tag: dev
          overwrite: true
      - name: Upload HAMR dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-mac-arm64.tar.xz
          asset_name: sireum-ive-vscodium-mac-arm64.tar.xz
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-arm64
          asset_name: sireum-cli-mac-arm64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-arm64.tar.xz
          asset_name: sireum-ive-mac-arm64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload HAMR Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-mac-arm64.tar.xz
          asset_name: sireum-ive-vscodium-mac-arm64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-macos-amd64:
    runs-on: macOS-13
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          submodules: recursive
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          "$SIREUM_HOME/bin/init.sh"
          "$SIREUM_HOME/bin/sireum" setup vscode --extensions "mhutchie.git-graph,ms-python.python,scalameta.metals,rust-lang.rust-analyzer"
          "$SIREUM_HOME/bin/build.cmd" native distro --mac --pack --vscodium
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-cli-mac-amd64
          mv "$SIREUM_HOME/distro/mac.tar.xz" sireum-ive-mac-amd64.tar.xz
          mv "$SIREUM_HOME/distro/sireum-ive-vscodium-mac-amd64.tar.xz" .
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-amd64
          asset_name: sireum-cli-mac-amd64
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-amd64.tar.xz
          asset_name: sireum-ive-mac-amd64.tar.xz
          tag: dev
          overwrite: true
      - name: Upload HAMR dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-mac-amd64.tar.xz
          asset_name: sireum-ive-vscodium-mac-amd64.tar.xz
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-mac-amd64
          asset_name: sireum-cli-mac-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-mac-amd64.tar.xz
          asset_name: sireum-ive-mac-amd64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload HAMR Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-mac-amd64.tar.xz
          asset_name: sireum-ive-vscodium-mac-amd64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true

  ci-distro-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Enable git config core.longpaths
        run: git config --system core.longpaths true
      - name: Clean
        shell: cmd
        run: |
          if exist "%GITHUB_WORKSPACE%\Sireum" rmdir /s/q "%GITHUB_WORKSPACE%\Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          submodules: recursive
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"
      - name: Build
        shell: cmd
        run: |
          set SIREUM_HOME=%GITHUB_WORKSPACE%\Sireum
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call "%SIREUM_HOME%\bin\init.bat"
          call "%SIREUM_HOME%\bin\sireum.bat" setup vscode --extensions "mhutchie.git-graph,ms-python.python,scalameta.metals,rust-lang.rust-analyzer"
          call "%SIREUM_HOME%\bin\build.cmd" native distro --win --pack --vscodium
          move "%SIREUM_HOME%\bin\win\sireum.exe" "%GITHUB_WORKSPACE%\sireum-cli-win-amd64.exe"
          move "%SIREUM_HOME%\distro\win.zip" "%GITHUB_WORKSPACE%\sireum-ive-win-amd64.zip"
          move "%SIREUM_HOME%\distro\sireum-ive-vscodium-win-amd64.zip" "%GITHUB_WORKSPACE%\"
      - name: Upload CLI dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-win-amd64.exe
          asset_name: sireum-cli-win-amd64.exe
          tag: dev
          overwrite: true
      - name: Upload IVE dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-win-amd64.zip
          asset_name: sireum-ive-win-amd64.zip
          tag: dev
          overwrite: true
      - name: Upload HAMR dev
        if: github.ref_type != 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-win-amd64.zip
          asset_name: sireum-ive-vscodium-win-amd64.zip
          tag: dev
          overwrite: true
      - name: Upload CLI Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-cli-win-amd64.exe
          asset_name: sireum-cli-win-amd64.exe
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload IVE Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-win-amd64.zip
          asset_name: sireum-ive-win-amd64.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload HAMR Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-ive-vscodium-win-amd64.zip
          asset_name: sireum-ive-vscodium-win-amd64.zip
          tag: ${{ github.ref }}
          overwrite: true
