name: Install

on: [push]

jobs:

  ci-jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Init
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          bin/init.sh
      - name: Trigger jitpack
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          timeout 90s bin/build.cmd jitpack || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      - name: Sleep for 15 minutes
        run: sleep 900s
        shell: bash

  ci-linux-install:
    needs: ci-jitpack
    runs-on: linux-latest
    steps:
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir "foo bar"
          cd "foo bar"
          (DIR=Sireum && export SIREUM_V=master && rm -fR $DIR && mkdir -p $DIR/bin && cd $DIR/bin && curl -JLso init.sh https://raw.githubusercontent.com/sireum/kekinian/$SIREUM_V/bin/init.sh && bash init.sh)
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "$SIREUM_HOME/bin/sireum" proyek ive "logika examples"
          "logika examples/bin/verify.cmd"

  ci-macos-install:
    needs: ci-jitpack
    runs-on: macOS-latest
    steps:
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir "foo bar"
          cd "foo bar"
          (DIR=Sireum && export SIREUM_V=master && rm -fR $DIR && mkdir -p $DIR/bin && cd $DIR/bin && curl -JLso init.sh https://raw.githubusercontent.com/sireum/kekinian/$SIREUM_V/bin/init.sh && bash init.sh)
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "$SIREUM_HOME/bin/sireum" proyek ive "logika examples"
          "logika examples/bin/verify.cmd"

  ci-windows-install:
    needs: ci-jitpack
    runs-on: windows-latest
    steps:
      - name: Test
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          md "foo bar"
          cd "foo bar"
          cmd /V /C "set DIR=Sireum&& set SIREUM_V=master&& (if exist !DIR! rd /S /Q !DIR!) && md !DIR!\bin && cd !DIR!\bin && curl -JLso init.bat https://raw.githubusercontent.com/sireum/kekinian/!SIREUM_V!/bin/init.bat && init.bat"
          set SIREUM_HOME=%GITHUB_WORKSPACE%\foo bar\Sireum
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "%SIREUM_HOME%\bin\sireum.bat" proyek ive "logika examples"
          "logika examples\bin\verify.cmd"
