name: Install

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  ci-install-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir "foo bar"
          cd "foo bar"
          (DIR=Sireum && export SIREUM_V=master && rm -fR $DIR && mkdir -p $DIR/bin && cd $DIR/bin && curl -JLso init.sh https://raw.githubusercontent.com/sireum/kekinian/$SIREUM_V/bin/init.sh && bash init.sh)
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "$SIREUM_HOME/bin/sireum" proyek ive "logika examples"
          "logika examples/bin/verify.cmd"
      - name: Native
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          "$SIREUM_HOME/bin/sireum" --native
          mv "$SIREUM_HOME/bin/linux/sireum" sireum-linux-amd64
      - name: Upload Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-linux-amd64
          path: sireum-linux-amd64
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-linux-amd64
          asset_name: sireum-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true

  ci-install-macos-arm64:
    runs-on: macOS-latest
    steps:
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir "foo bar"
          cd "foo bar"
          (DIR=Sireum && export SIREUM_V=master && rm -fR $DIR && mkdir -p $DIR/bin && cd $DIR/bin && curl -JLso init.sh https://raw.githubusercontent.com/sireum/kekinian/$SIREUM_V/bin/init.sh && bash init.sh)
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "$SIREUM_HOME/bin/sireum" proyek ive "logika examples"
          "logika examples/bin/verify.cmd"
      - name: Native
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          "$SIREUM_HOME/bin/sireum" --native
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-mac-arm64
      - name: Upload Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-mac-arm64
          path: sireum-mac-arm64
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-mac-arm64
          asset_name: sireum-mac-arm64
          tag: ${{ github.ref }}
          overwrite: true

  ci-install-macos-amd64:
    runs-on: macOS-13
    steps:
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir "foo bar"
          cd "foo bar"
          (DIR=Sireum && export SIREUM_V=master && rm -fR $DIR && mkdir -p $DIR/bin && cd $DIR/bin && curl -JLso init.sh https://raw.githubusercontent.com/sireum/kekinian/$SIREUM_V/bin/init.sh && bash init.sh)
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "$SIREUM_HOME/bin/sireum" proyek ive "logika examples"
          "logika examples/bin/verify.cmd"
      - name: Native
        run: |
          cd $GITHUB_WORKSPACE
          export SIREUM_HOME="$GITHUB_WORKSPACE/foo bar/Sireum"
          "$SIREUM_HOME/bin/sireum" --native
          mv "$SIREUM_HOME/bin/mac/sireum" sireum-mac-amd64
      - name: Upload Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-mac-amd64
          path: sireum-mac-amd64
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-mac-amd64
          asset_name: sireum-mac-amd64
          tag: ${{ github.ref }}
          overwrite: true

  ci-install-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Test
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          md "foo bar"
          cd "foo bar"
          cmd /V /C "set DIR=Sireum&& set SIREUM_V=master&& (if exist !DIR! rd /S /Q !DIR!) && md !DIR!\bin && cd !DIR!\bin && curl -JLso init.bat https://raw.githubusercontent.com/sireum/kekinian/!SIREUM_V!/bin/init.bat && init.bat"
          set SIREUM_HOME=%GITHUB_WORKSPACE%\foo bar\Sireum
          cd ..
          git clone https://github.com/sireum/logika-examples.git "logika examples"
          "%SIREUM_HOME%\bin\sireum.bat" proyek ive "logika examples"
          "logika examples\bin\verify.cmd"
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"
      - name: Native
        shell: cmd
        run: |
          set SIREUM_HOME=%GITHUB_WORKSPACE%\foo bar\Sireum
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call "%SIREUM_HOME%\bin\sireum.bat" --native
          move "%SIREUM_HOME%\bin\win\sireum.exe" "%GITHUB_WORKSPACE%\sireum-win-amd64.exe"
      - name: Upload Artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: sireum-win-amd64.exe
          path: sireum-win-amd64.exe
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
          overwrite: true
          include-hidden-files: false
      - name: Upload Release
        if: github.ref_type == 'tag'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sireum-win-amd64.exe
          asset_name: sireum-win-amd64.exe
          tag: ${{ github.ref }}
          overwrite: true
