name: Jitpack

on:
  push:
  workflow_dispatch:

jobs:

  ci-jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE"/.*
          rm -fR "$GITHUB_WORKSPACE"/*
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Init
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          bin/init.sh
      - name: Trigger jitpack
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          timeout 90s bin/build.cmd jitpack || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
