name: Jitpack

on:
  push:
  workflow_dispatch:

jobs:

  ci-jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        run: |
          git clone --recursive https://github.com/sireum/kekinian Sireum
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: Sireum/bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: Sireum/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: Sireum/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-coursier
      - name: Init
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/Sireum/cache/coursier
          cd $GITHUB_WORKSPACE/Sireum
          bin/init.sh
      - name: Trigger jitpack
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/Sireum/cache/coursier
          cd $GITHUB_WORKSPACE/Sireum
          timeout 90s bin/build.cmd jitpack || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
