name: Linux-CompCert

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE"/.*
          rm -fR "$GITHUB_WORKSPACE"/*
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-coursier
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v3
        with:
          path: |
            bin/linux/cvc
            bin/linux/.cvc.ver
            bin/linux/cvc5
            bin/linux/.cvc5.ver
            bin/linux/z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-smt2
      - name: Cache CompCert
        id: cache-compcert
        uses: actions/cache@v3
        with:
          path: |
            bin/linux/.compcert.ver
            bin/linux/.coq.ver
            bin/linux/.menhir.ver
            bin/linux/.opam.ver
            bin/linux/.opam
            bin/linux/opam
          key: ${{ runner.os }}-${{ hashFiles('bin/install/opam.cmd','bin/install/compcert.cmd') }}-compcert
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          .ci/linux-compcert.sh
