name: Linux

on: [push]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v2
        with:
          path: bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v2
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v2
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Cache Graal
        id: cache-graal
        uses: actions/cache@v2
        with:
          path: bin/linux/graal
          key: ${{ runner.os }}-${{ hashFiles('bin/install/graal.cmd') }}-graal
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v2
        with:
          path: |
            bin/linux/cvc
            bin/linux/.cvc.ver
            bin/linux/cvc5
            bin/linux/.cvc5.ver
            bin/linux/z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-smt2
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          .ci/build.sh
          .ci/build.sh test
          .ci/linux-native.sh
          rm bin/linux/sireum
          bin/install/ffmpeg-libs.cmd
