name: macOS-CompCert

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:

  ci:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-coursier
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v3
        with:
          path: |
            bin/mac/cvc
            bin/mac/cvc5
            bin/mac/.cvc.ver
            bin/mac/.cvc5.ver
            bin/mac/z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-smt2
      - name: Cache CompCert
        id: cache-compcert
        uses: actions/cache@v3
        with:
          path: |
            bin/mac/.compcert.ver
            bin/mac/.coq.ver
            bin/mac/.menhir.ver
            bin/mac/.opam.ver
            bin/mac/.opam
            bin/mac/opam
          key: ${{ runner.os }}-${{ hashFiles('bin/install/opam.cmd','bin/install/compcert.cmd') }}-compcert
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          .ci/macOS-compcert.sh
