name: macOS

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:

  ci:
    runs-on: macOS-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          recursive: true
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: Sireum/bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: Sireum/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: Sireum/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-coursier
      - name: Cache Graal
        id: cache-graal
        uses: actions/cache@v3
        with:
          path: Sireum/bin/mac/graal
          key: ${{ runner.os }}-${{ hashFiles('Sireum/bin/install/graal.cmd') }}-graal
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v3
        with:
          path: |
            Sireum/bin/mac/cvc
            Sireum/bin/mac/cvc5
            Sireum/bin/mac/.cvc.ver
            Sireum/bin/mac/.cvc5.ver
            Sireum/bin/mac/z3
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-smt2
      - name: Cache OSATE
        id: cache-osate
        uses: actions/cache@v3
        with:
          path: Sireum/bin/mac/osate.app
          key: ${{ runner.os }}-${{ hashFiles('Sireum/hamr/codegen/jvm/src/main/resources/phantom_versions.properties') }}-osate
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/Sireum/cache/coursier
          cd $GITHUB_WORKSPACE/Sireum
          .ci/build.sh && .ci/build.sh test-verify
          #.ci/mac-native.sh # need large runner
          #rm bin/mac/sireum
