name: macOS-CompCert

on: [push]

jobs:

  ci:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v2
        with:
          path: bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v2
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v2
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-coursier
      - name: Cache CompCert
        id: cache-compcert
        uses: actions/cache@v2
        with:
          path: |
            bin/mac/.opam
            bin/mac/opam
            bin/mac/.compcert.ver
          key: ${{ runner.os }}-${{ hashFiles('bin/install/compcert.cmd') }}-compcert
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v2
        with:
          path: |
            bin/mac/cvc4
            bin/mac/.cvc4.ver
            bin/mac/z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-smt2
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          .ci/macOS-compcert.sh
