name: macOS-CompCert

on: [push]

jobs:

  ci:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v2
        with:
          path: bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v2
        with:
          path: bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v2
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-compcert-coursier
      - name: Cache CompCert
        id: cache-compcert
        uses: actions/cache@v2
        with:
          path: |
            bin/mac/.opam
            bin/mac/opam
            bin/mac/.compcert.ver
          key: ${{ runner.os }}-${{ hashFiles('bin/install/compcert.cmd') }}-compcert
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          .ci/macOS-compcert.sh
