name: m2

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[distro]')"
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          submodules: recursive
      - name: Build Jar & m2
        run: |
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          rm -fR "$GITHUB_WORKSPACE/.m2" $HOME/.m2
          "$SIREUM_HOME/bin/build.cmd" m2
          mv $HOME/.m2 "$GITHUB_WORKSPACE/.m2"
          zip -r org.sireum.m2.zip .m2
      - name: Upload m2 dev
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: org.sireum.m2.zip
          asset_name: org.sireum.m2.zip
          tag: dev
          overwrite: true
      - name: Trigger JitPack
        run: |
          cd "$GITHUB_WORKSPACE"
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          timeout 10s "$SIREUM_HOME/bin/build.cmd" jitpack || true
