name: Web

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  ci-web:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Publish
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/sireum/website.git
          cd website
          ./publish.sh
