name: CI

on: [push]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Z3
        id: cache-z3
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/linux/z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-z3
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Cache Graal
        id: cache-graal
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/linux/graal
          key: ${{ runner.os }}-${{ hashFiles('bin/install/graal.cmd') }}-graal
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test
      - name: Build Native
        run: |
          bin/build.cmd native
          bin/linux/upx -9 bin/linux/sireum
          bin/linux/sireum

  build-mac:
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Z3
        id: cache-z3
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/mac/z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-z3
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Cache Graal
        id: cache-graal
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/mac/graal
          key: ${{ runner.os }}-${{ hashFiles('bin/install/graal.cmd') }}-graal
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test
      - name: Build Native
        run: |
          bin/build.cmd native
          bin/mac/upx -9 bin/mac/sireum
          bin/mac/sireum

  build-windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$($env:GITHUB_WORKSPACE)"
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\bin\win\java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Z3
        id: cache-z3
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\bin\win\z3
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-z3
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\bin\scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\cache\coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Cache Graal
        id: cache-graal
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\bin\win\graal
          key: ${{ runner.os }}-${{ hashFiles('bin/install/graal.cmd') }}-graal
      - name: Test
        shell: cmd
        run: |
          set COURSIER_CACHE=%GITHUB_WORKSPACE%\cache\coursier
          cd /d %GITHUB_WORKSPACE%
          git submodule update --init --recursive
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          bin\build.cmd test
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Build Native
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call bin\build.cmd native
          bin\win\upx.exe -9 bin\win\sireum.exe
          bin\sireum

  skip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip action]')"
    steps:
      - run: |
          echo Skipped
